import os
from dotenv import load_dotenv

load_dotenv()

class Config:
    SECRET_KEY = os.getenv('SECRET_KEY')
    SQLALCHEMY_DATABASE_URI = 'sqlite:///database.db'
    DISCORD_CLIENT_ID = os.getenv('DISCORD_CLIENT_ID')
    DISCORD_CLIENT_SECRET = os.getenv('DISCORD_CLIENT_SECRET')
    DISCORD_BOT_TOKEN = os.getenv('DISCORD_BOT_TOKEN')
    DISCORD_GUILD_ID = int(os.getenv('DISCORD_GUILD_ID'))
    DISCORD_REDIRECT_URI = os.getenv('DISCORD_REDIRECT_URI')
    DISCORD_ADMIN_ROLE_ID = os.getenv('DISCORD_ADMIN_ROLE_ID')
    DISCORD_CUR_ROLE_ID = os.getenv('DISCORD_CUR_ROLE_ID')
    DISCORD_ZAMCUR_ROLE_ID = os.getenv('DISCORD_ZAMCUR_ROLE_ID')
    DISCORD_GLMOD_ROLE_ID = os.getenv('DISCORD_GLMOD_ROLE_ID')
    DISCORD_STMOD_ROLE_ID = os.getenv('DISCORD_STMOD_ROLE_ID')
    DISCORD_CHECKHELPERS_ROLE_ID = os.getenv('DISCORD_CHECKHELPERS_ROLE_ID')
    DISCORD_MOD_ROLE_ID = os.getenv('DISCORD_MOD_ROLE_ID')
    DISCORD_MLMOD_ROLE_ID = os.getenv('DISCORD_MLMOD_ROLE_ID')
    DISCORD_HELPER_ROLE_ID = os.getenv('DISCORD_HELPER_ROLE_ID')